name: Build JSON Taxonomy

# Run this workflow on a push to main or on a schedule
on:
  push: # This triggers the workflow on any push to any branch
    branches:
      - actions-json-update
      - main
  # schedule:
  #   - cron: '0 0 1 * *'

jobs:
  update-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Give writing permission

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dependencies if your script requires any
      - name: Install dependencies
        run: |
          echo '..pytyon install..'
          #python -m pip install --upgrade pip
          #pip install -r requirements.txt  # Ensure a requirements file exists if needed

      # Run the Python script
      - name: Run taxonomy script
        run: |
          echo '...create json...'
          #python create_json_taxonomy.py

      # Commit and push changes if fungi_taxonomy.json was modified
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: create file
        run: |
          echo 'Hello' > world.txt

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.NYMS_PAT }}
        run: |
          if [ -n "$(git status --porcelain fungi_taxonomy.json)" ]; then
            git add .
            git commit -m "ci: Update fungi_taxonomy.json"
            git push
          fi
